app:
    resource: "@AppBundle/Controller/"
    type:     annotation
wordpress:
    resource: "@AppBundle/Extensions/WordPress/"
    type:     annotation
check-connection:
    resource: "@AppBundle/Utils/"
    type: annotation
